### ISSUE TITLE
ParseError: Unable to connect to the Parse API

### ISSUE THREAD

**Issue by kashesandr** [leopq/gatsby-source-parse#2]
Hello! 

Basically works not stable for me, from run to run it might work or throw an error...

Any ideas why the error below might happen from time to time?

```
success createSchemaCustomization - 0.007s
ParseError: XMLHttpRequest failed: "Unable to connect to the Parse API"
    at handleError (/Users/kashesandr/WebstormProjects/belki/node_modules/gatsby-source-parse/node_modules/parse/lib/node/RESTController.js:429:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.exports.sourceNodes (/Users/kashesandr/WebstormProjects/belki/node_modules/gatsby-source-parse/gatsby-node.js:110:22) {
  code: 100
}
warn The gatsby-source-parse plugin has generated no Gatsby nodes. Do you need it?
```

**Comment by kashesandr** [comment]
The reason is that the current version "gatsby-source-parse" = "1.5.7" is incombatible with parse sdk v3.3.0
